### ISSUE TITLE
ERROR - Fatal Python error: Py_Initialize: can't initialize sys standard streams

### ISSUE THREAD

**Issue by cparg** [Amourspirit/python_ooo_dev_tools#487]
When I try to install OOO Development Tools 0.17.13 in LO 7.6.4.1 (RHEL8) I get following errors:
PYTHONPATH is unset 

```
2023-12-30 17:50:09,020 - uno_component - INFO - Pip is not installed. Attempting to install
2023-12-30 17:50:09,021 - ooodev_tools_pip.install.install_pip - INFO - Installing PIP via default installer
2023-12-30 17:52:54,994 - uno_component - INFO - Pip is not installed. Attempting to install
2023-12-30 17:52:54,994 - ooodev_tools_pip.install.install_pip - INFO - Installing PIP via default installer
2023-12-30 17:53:52,023 - uno_component - INFO - Pip is not installed. Attempting to install
2023-12-30 17:53:52,024 - ooodev_tools_pip.install.install_pip - INFO - Installing PIP via default installer
2023-12-30 17:53:52,561 - ooodev_tools_pip.install.pip_installers.default_installer - INFO - PIP installation file has been saved
2023-12-30 17:53:52,562 - ooodev_tools_pip.install.pip_installers.default_installer - INFO - Starting PIP installation…
2023-12-30 17:53:52,647 - ooodev_tools_pip.install.pip_installers.default_installer - ERROR - PIP installation has failed
2023-12-30 17:53:52,647 - ooodev_tools_pip.install.pip_installers.default_installer - ERROR - Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/opt/libreoffice7.6/program/python-core-3.8.17/lib/abc.py", line 64, in <module>
ModuleNotFoundError: No module named '_abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/libreoffice7.6/program/python-core-3.8.17/lib/io.py", line 52, in <module>
  File "/opt/libreoffice7.6/program/python-core-3.8.17/lib/abc.py", line 68, in <module>
  File "/opt/libreoffice7.6/program/python-core-3.8.17/lib/_py_abc.py", line 35
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
SyntaxError: invalid syntax

2023-12-30 17:53:52,648 - ooodev_tools_pip.install.pip_installers.default_installer - ERROR - PIP installation has failed
2023-12-30 17:53:52,709 - uno_component - INFO - Pip was not successfully installed
2023-12-30 17:53:52,709 - uno_component - INFO - OooDevRunner execution time: 1.549 seconds
```

... is there something missing in LO 7.6 Python packages !?

**Comment by Amourspirit** [comment]
I am not certain what is causing this error.
It seems like the `abc` module may be not available which does not make a lot of sense.

Do you have [APSO](https://python-ooo-dev-tools.readthedocs.io/en/main/guide/guide_apso.html) installed LibreOffice?
If so open the Console and try `import abc` and `import _abc`. Should not get any errors.

```
APSO python console [LibreOffice]
3.8.18 (default, Nov 30 2023, 14:52:54) [MSC v.1929 64 bit (AMD64)]
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> import _abc
>>> 
```

**Comment by Amourspirit** [comment]
Also I just noticed:
```
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
```

This appears to indicate that the `/` in the `_py_abc.py` file is an issue.
The `/` in methods is a recent addition to pythhon that indicates only key word arguments from this point on.
Could there be a bug in version `3.8.17` of pyhon? This will take a little more investigation.

**Comment by cparg** [comment]
Hello,
many thanks for looking at this.
Yes, APSO was installed.

... anything else I can help with ?
Christian

**Comment by Amourspirit** [comment]
> Also I just noticed:
> 
> ```
>     def __new__(mcls, name, bases, namespace, /, **kwargs):
>                                               ^
> ```
> 
> This appears to indicate that the `/` in the `_py_abc.py` file is an issue. The `/` in methods is a recent addition to python that indicates only key word arguments from this point on. Could there be a bug in version `3.8.17` of pyhon? This will take a little more investigation.

My mistake. `/` is a [positional only indicator](https://docs.python.org/3.8/whatsnew/3.8.html#positional-only-parameters) implement in Python `3.8`. It should work, but seems is an issue here.

**Comment by Amourspirit** [comment]
> Hello, many thanks for looking at this. Yes, APSO was installed.
> 
> ... anything else I can help with ? Christian

Did you try the import manually?

```
APSO python console [LibreOffice]
3.8.18 (default, Nov 30 2023, 14:52:54) [MSC v.1929 64 bit (AMD64)]
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> import _abc
>>> 
```

**Comment by cparg** [comment]
Hello,

abc imports w/o problems on the APSO Python console :

```
APSO python console [LibreOffice]
3.8.18 (default, Dec  1 2023, 09:10:43) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc
>>> import _abc
>>> 
```

**Comment by cparg** [comment]
Note: Python version slightly changed from the original description because I upgraded LO to the latest version meanwhile.

**Comment by Amourspirit** [comment]
> Note: Python version slightly changed from the original description because I upgraded LO to the latest version meanwhile.

Is the issue still there since you upgraded?

**Comment by cparg** [comment]
Yes, it was there before and after the LO Upgrade.

**Comment by Amourspirit** [comment]
Would you mind putting the extension log level to debug and trying again.
The higher level debug log may reveal more details.

Also download the latest `oxt` file directly from the [project source](https://github.com/Amourspirit/libreoffice_ooodev_ext/tree/main/dist) directory.

**Comment by Amourspirit** [comment]
If the issue presist you could always pip install [ooo-dev-tools](https://pypi.org/project/ooo-dev-tools/).

Also note there is an extension just for pip installing in LibeOffice as well, [zaz-pip](https://git.cuates.net/elmau/zaz-pip/src/branch/master/extension).
